import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Welcome from "@/components/Welcome";
import User from "@/components/User";
import Description from "@/components/Description";
import Pet from "@/components/Pet";
import Counter from "@/components/Counter";
import UserForm from "@/components/UserForm";
import ComponentePai from "@/components/ComponentePai";
import Children from "@/components/Children";
import TaskList from "@/components/TaskList";

export default function Home() {
  return (
    // fragment -envolve as teags que contem o conteudo do site
    <>
      <Head>
        <title>Fundamento do react</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World! Meu primeiro site em react</h1>
        <hr />
        <Welcome />
        <User />
        <hr /><br />
        <Description
          city="Registro"
          age={19}
          email="andreialda7@gmail.com"
        />
        <br />
        <Pet name="Lola" breed="Pincher" age={4} />
        <br />
        <Counter />
        <br />
        <UserForm />
        <br />  
        <br />  
        <ComponentePai />
        <br />
        <br />
        <Children>
          <div>
            <p>Este é o conteúdo filho passado para o componente Children.</p>
          </div>  
        </Children>
        <br />
        <br />
        <TaskList 
        tasks={ [
          {
            id: "1",
            text: "Pagar contas",
          },
          {
            id: "2",
            text: "Fazer compras no mercado",
          },
          {
            id: "3",
            text: "Lavar o carro",
          },
          {
            id: "4",
            text: "Estudar React",
          },
        ]}
        />
        <br />
        <br />
      
      </main>
    </>
  );
}
